#!/usr/bin/bash

echo "Configuring for:"
echo "PHP Version:             8.4"
echo "PHP Api Version:         20240924"
echo "Zend Module Api No:      20240924"
echo "Zend Extension Api No:   420240924"

exit 0
